### PR TITLE
Preparing for the repo split.

### PR DESCRIPTION
**Pull request by andersio**

### CODE REVIEW

**Comment by andersio** [comment]
screen shot 2016-09-11 at 5 07 39 pm

I've scraped all the texts and now it is pointing people directly to the repos... Would be glad to know your thoughts.

@ReactiveCocoa/reactivecocoa

**Comment by mdiep** [comment]
It should say _Functional Reactive Programming **inspired* frameworks_

**Comment by mdiep** [comment]
I think short descriptions next to each would be useful, personally.

**Comment by andersio** [comment]
Demo is updated: https://andersio.github.io/rac-portal/

**Comment by mdiep** [comment]
Looks good to me. 👍🏻

**Pull request merged**
